name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} Run GitHub Actions to upload docker image 🚀
on: 
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository code
      uses: actions/checkout@v4
    
    - name: build and tag image
      run: |
        docker build -t ${{secrets.USERNAME}}/uas-pcc-galang-2024:latest -f Dockerfile .
    
    - name: push to dockerhub
      run: docker login -u ${{secrets.USERNAME}} -p ${{secrets.ACCESS_TOKEN}} && docker push ${{secrets.USERNAME}}/uas-pcc-galang-2024:latest